#ifndef AUTOGRAPH_CONSTANTS_H
#define AUTOGRAPH_CONSTANTS_H

#define DIGEST_SIZE 64
#define FINGERPRINT_SIZE 32
#define IKM_SIZE 32
#define INDEX_SIZE 4
#define INFO_SIZE 9
#define NONCE_SIZE 12
#define OKM_SIZE 64
#define PADDING_BLOCK_SIZE 16
#define PADDING_BYTE 128
#define PRIVATE_KEY_SIZE 32
#define PUBLIC_KEY_SIZE 32
#define SALT_SIZE 64
#define SECRET_KEY_SIZE 32
#define SHARED_SECRET_SIZE 32
#define SIGNATURE_SIZE 64
#define SIZE_SIZE 4
#define STATE_SIZE 2048
#define TAG_SIZE 16

#define HELLO_SIZE 64
#define KEY_PAIR_SIZE 64
#define SAFETY_NUMBER_SIZE 64

#define FINGERPRINT_ITERATIONS 5200
#define FINGERPRINT_DIVISOR 100000

#define INFO \
  { 97, 117, 116, 111, 103, 114, 97, 112, 104 }

#define IDENTITY_KEY_PAIR_OFFSET 0
#define IDENTITY_PUBLIC_KEY_OFFSET 32
#define THEIR_IDENTITY_KEY_OFFSET 64
#define SENDING_NONCE_OFFSET 96
#define SENDING_INDEX_OFFSET 104
#define SENDING_KEY_OFFSET 108
#define RECEIVING_NONCE_OFFSET 140
#define RECEIVING_INDEX_OFFSET 148
#define RECEIVING_KEY_OFFSET 152

#define SKIPPED_INDEXES_MIN_OFFSET 184
#define SKIPPED_INDEXES_MAX_OFFSET 2044

#define EPHEMERAL_KEY_PAIR_OFFSET 184
#define EPHEMERAL_PUBLIC_KEY_OFFSET 216
#define THEIR_EPHEMERAL_KEY_OFFSET 248

#endif
